# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:          
          pkg-manager: pipenv
      - run:
          name: Install deps
          command: pipenv sync --dev --system
      - run:
          name: Run linter
          command: pipenv run flake8 .
      - run:
          name: Check formatting
          command: pipenv run black --check . && pipenv run isort --check .
      - run:
          name: Check static types
          command: pipenv run mypy .
     
workflows:
  main:
    jobs:
      - build
